version: "3.8"

services:

  phpfpm:
    build:
      args:
        NODE: 14.8.0
        UID: 1000
        USER: skel
        VERSION: 7.2
      context: build/dev
      dockerfile: Dockerfile
    image: phpfpm
    container_name: phpfpm-app

    command: >
      bash -c "composer install
      && npm install
      && php src/info.php"

    working_dir: /var/www/
    volumes:
      - ./:/var/www

    networks:
      - appdata


networks:

  appdata:
    driver: bridge