version: '3.8'

services:

  # Nginx Web Server #
  nginx:
    build:
      context: containers/nginx
    container_name: bones_nginx
    restart: always
    volumes:
      - ..:/var/www
    environment:
      DOCUMENT_ROOT: /var/www
      VIRTUAL_HOST: php.test
    ports:
      - "8086:80"
    depends_on:
      - php

  # PHP Server #
  php:
    build:
      context: containers/php
    container_name: bones_php
    restart: always
    volumes:
      - ..:/var/www
    tty: true