version: '3'

services:

  # Nginx Web Server #
  nginx:
    build:
      context: containers/nginx
    container_name: bones_nginx
    restart: always
    volumes:
      - ..:/var/www
    environment:
      DOCUMENT_ROOT: /var/www
      VIRTUAL_HOST: php.test
    ports:
      - "8086:80"
    depends_on:
      - php

  # PHP Server #
  php:
    build:
      context: containers/php
    container_name: bones_php
    restart: always
    volumes:
      - ..:/var/www
    tty: true
    depends_on:
      - mysql

  # Database Server #
  mysql:
    build:
      context: containers/mysql
    container_name: bones_mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: iods
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    ports:
      - "3307:3306"

volumes:
  db: